on:
  - pull_request

name: Test

jobs:
  test:
    name: Test
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.19

      - name: download deps
        run: go get .

      - name: Test
        run: go test

  build-binary:
    name: Build multi-architecture binary
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.19

      - name: download deps
        run: go get .

      - name: Build
        run: ./build.sh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: |
            gradle-subproject-resolver-macos
            gradle-subproject-resolver-linux-amd64
            gradle-subproject-resolver-linux-arm64
